grid_map_visualizations:

  - name: elevation_cloud
    type: point_cloud
    params:
     layer: elevation

  - name: upper_bound_cloud
    type: point_cloud
    params:
     layer: upper_bound

  - name: lower_bound_cloud
    type: point_cloud
    params:
     layer: lower_bound

  - name: map_region
    type: map_region
    params:
     color: 16777215
     line_width: 0.003

  - name: elevation_grid
    type: occupancy_grid
    params:
      layer: elevation
      data_min: -0.15
      data_max: 1.0

  - name: error_grid
    type: occupancy_grid
    params:
      layer: error
      data_min: -0.15
      data_max: 0.15

  - name: surface_normals
    type: vectors
    params:
      layer_prefix: normal_
      position_layer: elevation
      scale: 0.06
      line_width: 0.005
      color: 15600153 # red

  - name: elevation_cells
    type: grid_cells
    params:
      layer: elevation
      lower_threshold: -0.08
      upper_threshold: 0.0
