# PID gains for the steer_bot_hardware_gazebo plugin.
gains:
    wheel_br_to_motor_br:
        p: 100000.0
        d: 10.0
        i: 0.50
        i_clamp: 3.0
    wheel_bl_to_motor_bl:
        p: 100000.0
        d: 10.0
        i: 0.50
        i_clamp: 3.0

