# shutdown_costmaps: false
# controller_frequency: 10.0
# planner_patience: 5.0
# controller_patience: 15.0
# conservative_reset_dist: 3.0
# planner_frequency: 5.0
# oscillation_timeout: 10.0
# oscillation_distance: 0.2


controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 0.0
# planner_frequency: 5.0
oscillation_timeout: 10.0
oscillation_distance: 0.2
oscillation_patience: 10.0


#shutdown_costmaps: true
#controller_frequency: 10.0
#planner_patience: 5.0
#controller_patience: 15.0
#conservative_reset_dist: 3.0
#planner_frequency: 5.0

 #oscillation_timeout: 10.0  #<- process has died
 #oscillation_distance: 0.2

max_planning_retries : 1
recovery_behavior_enabled : true
#shutdown_costmaps: true